#ifndef CONFIG_WINDOW_PROPERTIES_H
#define CONFIG_WINDOW_PROPERTIES_H

#define BORDER_SIZE            1
#define WINDOW_WIDTH           800
#define WINDOW_HEIGHT          600
#define BORDER_COLOR_UNFOCUSED 0x666666
#define BORDER_COLOR_FOCUSED   0xEEEEEE

#endif
